#!/usr/bin/env python3
"""
Exact verifier for the C45 Romanoff upper-density bound
    overline d(A) < 0.490249407811155.

The script verifies the 36-prime finite obstruction certificate described in
this PR. It reads a 13-prime seed histogram generated from first principles by
generate_seed_histogram.cpp, applies the exact coprime-order cluster updates, and then performs the final rational inequality
check using a rigorous lower bound for log(2).

No floating point arithmetic is used in any assertion. Decimal arithmetic is
used only for human-readable output.
"""
from __future__ import annotations

from bisect import bisect_right
from collections import Counter
from decimal import Decimal, getcontext
from fractions import Fraction
from math import lcm, prod
from pathlib import Path
import sys

BASE_PRIMES = [3, 5, 7, 11, 13, 17, 19, 29, 31, 37, 41, 61, 73]

ADDED_CLUSTERS = {
    11: [23, 89],
    13: [8191],
    23: [47, 178481],
    29: [233, 1103, 2089],
    37: [223],
    43: [431, 9719],
    47: [2351, 4513],
    73: [439],
    83: [167],
    131: [263],
    179: [359, 1433],
    191: [383],
    239: [479, 1913, 5737, 176383],
}

ALL_PRIMES = sorted(BASE_PRIMES + [q for qs in ADDED_CLUSTERS.values() for q in qs])

EXPECTED_M = int("77647987881031766653638954957516345525837812179564689471444926820062741622939917219985")
EXPECTED_PHI = int("20439232269111000863616155005739376004784767346781800757207096895187762282496000000000")
EXPECTED_T = int("116570053844283433719485160")

CURRENT_REPO_UPPER = Fraction(490341088858244, 10**15)
NEW_DISPLAYED_UPPER = Fraction(490249407811155, 10**15)


def load_seed_histogram(path: Path) -> dict[int, int]:
    """Read the seed histogram generated by generate_seed_histogram.cpp.

    Expected format: one "nu count" pair per nonblank line. Lines starting with
    # are ignored.
    """
    hist: dict[int, int] = {}
    for lineno, raw in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split()
        if len(parts) != 2:
            raise ValueError(f"{path}:{lineno}: expected two columns, got {raw!r}")
        nu = int(parts[0])
        count = int(parts[1])
        if not (0 <= nu <= 2520):
            raise ValueError(f"{path}:{lineno}: nu out of range: {nu}")
        if count <= 0:
            raise ValueError(f"{path}:{lineno}: nonpositive count: {count}")
        if nu in hist:
            raise ValueError(f"{path}:{lineno}: duplicate nu value: {nu}")
        hist[nu] = count
    if not hist:
        raise ValueError(f"{path}: empty histogram")
    return hist

def ord_mod_2(q: int) -> int:
    """Return the multiplicative order of 2 modulo the odd prime q."""
    x = 2 % q
    d = 1
    while x != 1:
        x = (x * 2) % q
        d += 1
    return d


def cluster_polynomial(order: int, primes: list[int]) -> dict[int, int]:
    """Return H_order as a dictionary {h: c_h}.

    For a cluster of primes with common order d=order, c_h is the number of
    residue choices modulo the cluster primes that leave exactly h of the d
    exponent classes admissible.

    The DP tracks only the number s of removed exponent classes. If s classes
    have already been removed, then for the next prime q:
      * q-d non-power residues remove no class,
      * s power residues remove an already removed class,
      * d-s power residues remove a new class.
    """
    d = order
    dist: dict[int, int] = {0: 1}  # s removed classes -> count
    for q in primes:
        assert ord_mod_2(q) == d, (q, ord_mod_2(q), d)
        new: Counter[int] = Counter()
        for s, count in dist.items():
            non_power = q - d
            if non_power:
                new[s] += count * non_power
            if s:
                new[s] += count * s
            if s < d:
                new[s + 1] += count * (d - s)
        dist = dict(new)
    poly = {d - s: count for s, count in dist.items()}
    assert sum(poly.values()) == prod(primes)
    return poly


def multiplier_distribution() -> Counter[int]:
    """Distribution of the multiplicative factor applied to the seed nu values."""
    mult: Counter[int] = Counter({1: 1})
    for order, primes in ADDED_CLUSTERS.items():
        poly = cluster_polynomial(order, primes)
        new: Counter[int] = Counter()
        for m, weight in mult.items():
            for h, c in poly.items():
                new[m * h] += weight * c
        mult = new
    return mult


def log2_lower_bound(terms: int = 40) -> Fraction:
    """Rational lower bound for log(2).

    Uses log(2)=2*sum_{j>=0} 1/((2j+1)3^(2j+1)). The finite partial sum is a
    strict lower bound, so its reciprocal is a rigorous upper bound for 1/log(2).
    """
    return sum(Fraction(2, (2*j + 1) * 3**(2*j + 1)) for j in range(terms))


def decimal(frac: Fraction, prec: int = 100) -> Decimal:
    getcontext().prec = prec
    return Decimal(frac.numerator) / Decimal(frac.denominator)


def main() -> None:
    seed_path = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("seed_histogram_13_prime.txt")
    base_histogram_13_prime = load_seed_histogram(seed_path)
    assert set(base_histogram_13_prime) <= set(range(2521))
    assert sum(base_histogram_13_prime.values()) == prod(BASE_PRIMES)

    M = prod(ALL_PRIMES)
    phi_M = prod(q - 1 for q in ALL_PRIMES)
    T = 1
    for q in ALL_PRIMES:
        T = lcm(T, ord_mod_2(q))

    assert M == EXPECTED_M
    assert phi_M == EXPECTED_PHI
    assert T == EXPECTED_T

    mult = multiplier_distribution()
    added_prime_product = prod(q for qs in ADDED_CLUSTERS.values() for q in qs)
    assert sum(mult.values()) == added_prime_product
    assert prod(BASE_PRIMES) * added_prime_product == M

    items = sorted(mult.items())
    factors = [h for h, _ in items]
    prefix_weight = [0]
    prefix_weighted_factor = [0]
    for h, weight in items:
        prefix_weight.append(prefix_weight[-1] + weight)
        prefix_weighted_factor.append(prefix_weighted_factor[-1] + weight * h)
    total_weight = prefix_weight[-1]

    log2_lb = log2_lower_bound(40)
    trivial_term = Fraction(1, 2 * M)
    prime_progression_scale = Fraction(1, T * phi_M) / log2_lb

    # For each seed nu and added multiplier h, the contribution is
    # min(1/(2M), nu*h/(T*phi(M)*log(2))). We use the rational upper bound
    # obtained from log2_lb. Prefix sums over h avoid constructing the full
    # final 36-prime histogram explicitly.
    S_upper = Fraction(0, 1)
    for nu, delta in base_histogram_13_prime.items():
        if nu == 0:
            continue
        threshold = trivial_term / (prime_progression_scale * nu)
        threshold_floor = threshold.numerator // threshold.denominator
        idx = bisect_right(factors, threshold_floor)
        small_weighted_factor = prefix_weighted_factor[idx]
        large_weight = total_weight - prefix_weight[idx]
        S_upper += delta * (
            prime_progression_scale * nu * small_weighted_factor
            + trivial_term * large_weight
        )

    assert S_upper < NEW_DISPLAYED_UPPER
    assert NEW_DISPLAYED_UPPER < CURRENT_REPO_UPPER

    print("36-prime Romanoff upper-density certificate")
    print(f"number of primes = {len(ALL_PRIMES)}")
    print(f"M = {M}")
    print(f"phi(M) = {phi_M}")
    print(f"T = {T}")
    print(f"seed histogram entries = {len(base_histogram_13_prime)}")
    print(f"added multiplier entries = {len(mult)}")
    print(f"rational upper sum = {decimal(S_upper)}")
    print(f"proved: upper density < {decimal(NEW_DISPLAYED_UPPER, 30)}")
    print(f"improvement over current displayed upper bound = {decimal(CURRENT_REPO_UPPER - NEW_DISPLAYED_UPPER, 30)}")


if __name__ == "__main__":
    main()
